### ISSUE TITLE
ModuleNotFoundError: No module named 'banal'

### ISSUE THREAD

**Issue by smrohrer** [alephdata/languagecodes#3]
# Steps to reproduce
1. Ran `pip install languagecodes` in a virtual environment with pip 21.2.4 and Python 3.7.6
```
(env) (base) scottrohrer@Scotts-MacBook-Air-2 Language-Indexing % pip install languagecodes
Collecting languagecodes
  Using cached languagecodes-1.1.0-py2.py3-none-any.whl (157 kB)
Installing collected packages: languagecodes
Successfully installed languagecodes-1.1.0
```
2. Attempted to `import languagecodes` in Python shell
```
(env) (base) scottrohrer@Scotts-MacBook-Air-2 Language-Indexing % python
Python 3.7.6 (default, Jan  8 2020, 13:42:34) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import languagecodes
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/scottrohrer/Documents/wikitongues/Language-Indexing/env/lib/python3.7/site-packages/languagecodes/__init__.py", line 2, in <module>
    from banal import ensure_list
ModuleNotFoundError: No module named 'banal'
>>> 
```

**Comment by pudo** [comment]
Looks like we were missing a dependency. Try doing `pip install --upgrade languagecodes` now.

**Comment by smrohrer** [comment]
Perfect, thank you!
